# Generated by Django 6.0.3 on 2026-03-25 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='time checked')),
            ],
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=5)),
                ('pub_date', models.DateTimeField(verbose_name='time checked')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.name')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='time recorded')),
                ('zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.zip')),
            ],
        ),
    ]
